language: php

notifications:
  email:
    on_success: never

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo # Rapid composer installation
  - travis_retry composer install --no-interaction
  - echo 'xdebug.overload_var_dump=0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer test-in-ci
