language: php

notifications:
  email:
    on_success: never

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test
